lore/urls.py
from __future__ import unicode_literals

from django.conf.urls import include, url
from django.contrib import admin

import importer.urls as importer_urls
import learningresources.urls as lore_urls
import cas.urls as cas_urls
import taxonomy.urls as taxonomy_urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', include(lore_urls)),
    url(r'^lore/', include(lore_urls)),
    url(r'^importer/', include(importer_urls)),
    url(r'^cas/', include(cas_urls)),
    url(r'^taxonomy/', include(taxonomy_urls, namespace="taxonomy")),
]

ui/urls.py
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

from ui.views import (
    welcome,
    create_repo,
    upload,
    repository_view,
    serve_static_assets,
    serve_resource_exports,
    repository_data_view,
)
import rest.urls as rest_urls
import cas.urls as cas_urls
from learningresources.models import STATIC_ASSET_PREFIX


urlpatterns = [
    url(r'^$', welcome, name='welcome'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/v1/', include(rest_urls)),
    url(r'^cas/', include(cas_urls)),
    url(r'^home/$', welcome, name='welcome'),
    url(r'^repositories/new/$', create_repo, name='create_repo'),
    url(
        r'^repositories/(?P<repo_slug>[-\w]+)/$',
        repository_view,
        name='repositories'
    ),
    url(
        r'^repositories/(?P<repo_slug>[-\w]+)/data/$',
        repository_data_view,
        name='repositories-data'
    ),
    url(r'^repositories/(?P<repo_slug>[-\w]+)/import/$',
        upload, name='upload'),
    url(r'^status/', include('server_status.urls')),
]

if (settings.DEFAULT_FILE_STORAGE ==
        'storages.backends.overwrite.OverwriteStorage'):
    urlpatterns.append(
        url(r'^media/{assets}/(?P<path>.+)$'.format(
            assets=STATIC_ASSET_PREFIX
        ),
            serve_static_assets,
            name='media')
    )
    urlpatterns.append(
        url(r'^media/resource_exports/(?P<path>.+)$',
            serve_resource_exports,
            name='media')
    )

learningresources/models.py
"""
Learning resources data model
"""

from __future__ import unicode_literals

import logging
# pylint currently has a bug which incorrectly flags this as an error
import six.moves.urllib.parse as urllib_parse  # pylint: disable=import-error

from django.db import models
from django.db import transaction
from django.contrib.auth.models import User
from django.utils.encoding import python_2_unicode_compatible
from django.shortcuts import get_object_or_404

from audit.models import BaseModel
from rest.util import default_slugify
from roles.api import roles_update_repo
from roles.permissions import RepoPermission
from lore.settings import LORE_PREVIEW_BASE_URL

log = logging.getLogger(__name__)

# defining the file path max length
FILE_PATH_MAX_LENGTH = 900
STATIC_ASSET_PREFIX = 'assets'
STATIC_ASSET_BASEPATH = STATIC_ASSET_PREFIX + '/{org}/{course_number}/{run}/'


class FilePathLengthException(Exception):
    """Custom Exception to handle long file paths"""


def static_asset_basepath(asset, filename):
    """
    Creates folder base path for given asset.

    Callback API defined by:
    https://docs.djangoproject.com/en/1.8/ref/models/fields/#django.db.models.FileField.upload_to
    Args:
        asset (StaticAsset): The model to create the name for.
        filename (unicode): The subpath and filename of ``asset.asset``
    Returns:
        (unicode): forward slash separated path to use below
            ``settings.MEDIA_ROOT``.
    """
    return (STATIC_ASSET_BASEPATH + '{filename}').format(
        org=asset.course.org,
        course_number=asset.course.course_number,
        run=asset.course.run,
        filename=filename
    )


def course_asset_basepath(course, filename):
    """
    Returns folder base path for given path.

    Callback API defined by:
    https://docs.djangoproject.com/en/1.8/ref/models/fields/#django.db.models.FileField.upload_to
    Args:
        course (Course): The model to create the name for.
        filename (unicode): The subpath and filename of the asset.
    Returns:
        (unicode): forward slash separated path to use below
            ``settings.MEDIA_ROOT``.
    """
    return (STATIC_ASSET_BASEPATH + '{filename}').format(
        org=course.org,
        course_number=course.course_number,
        run=course.run,
        filename=filename
    )


class Course(BaseModel):
    """
    A course on edX platform (MITx or residential).
    """
    repository = models.ForeignKey('Repository')
    org = models.TextField()
    course_number = models.TextField()
    run = models.TextField()
    imported_by = models.ForeignKey(User)

    class Meta:
        # pylint: disable=missing-docstring,too-few-public-methods
        unique_together = ("repository", "org", "course_number", "run")


class StaticAsset(BaseModel):
    """
    Holds static assets for a course (css, html, javascript, images, etc)
    """
    course = models.ForeignKey(Course)
    asset = models.FileField(
        upload_to=static_asset_basepath,
        max_length=FILE_PATH_MAX_LENGTH
    )

    def save(self, *args, **kwargs):
        """
        Handle file length properly
        It seems that Django FileField does not enforce the length
        """
        if len(self.asset.name) > FILE_PATH_MAX_LENGTH:
            raise FilePathLengthException(
                'File path is more than {} characters long'.format(
                    FILE_PATH_MAX_LENGTH
                )
            )
        super(StaticAsset, self).save(*args, **kwargs)


class LearningResourceContentXml(BaseModel):
    """
    The content XML for a LearningResource.
    """
    content_xml = models.TextField()


class LearningResource(BaseModel):
    """
    The units that compose an edX course:
    chapter, sequential, vertical, problem, video, html, etc.
    """
    course = models.ForeignKey(Course, related_name="resources")
    learning_resource_type = models.ForeignKey('LearningResourceType')
    static_assets = models.ManyToManyField(StaticAsset, blank=True)
    uuid = models.TextField()
    title = models.TextField()
    description = models.TextField(blank=True)
    _content_xml = models.TextField(db_column="content_xml", null=True)
    materialized_path = models.TextField()
    description_path = models.TextField(blank=True)
    url_path = models.TextField()
    parent = models.ForeignKey('self', null=True, blank=True)
    copyright = models.TextField()
    xa_nr_views = models.IntegerField(default=0)
    xa_nr_attempts = models.IntegerField(default=0)
    xa_avg_grade = models.FloatField(default=0)
    xa_histogram_grade = models.FloatField(default=0)
    url_name = models.TextField(null=True)
    content_xml_model = models.ForeignKey(LearningResourceContentXml)

    @property
    def content_xml(self):
        """
        The content XML for a LearningResource.
        """
        return self.content_xml_model.content_xml


@python_2_unicode_compatible
class LearningResourceType(BaseModel):
    """
    Learning resource type:
    chapter, sequential, vertical, problem, video, html, etc.
    """
    name = models.TextField(unique=True)

    def __str__(self):
        return self.name


class Repository(BaseModel):
    """
    A collection of learning resources
    that come from (usually tightly-related) courses.
    """
    name = models.CharField(max_length=256, unique=True)
    slug = models.SlugField(max_length=256, unique=True)
    description = models.TextField()
    created_by = models.ForeignKey(User)

    @transaction.atomic
    def save(self, *args, **kwargs):
        """
        Handle slugs and groups.
        """
        is_update = False
        if self.id is None or self.name != get_object_or_404(
                Repository, id=self.id).name:
            # if it is an update of the repository, need the old slug
            if self.id is not None:
                is_update = True
                old_slug = get_object_or_404(Repository, id=self.id).slug
            self.slug = default_slugify(
                self.name,
                Repository._meta.model_name,
                lambda slug: Repository.objects.filter(slug=slug).exists()
            )
            # check if it's necessary to initialize the permissions
        new_repository = super(Repository, self).save(*args, **kwargs)
        if is_update:
            roles_update_repo(self, old_slug)
        return new_repository

    class Meta:  # pylint: disable=missing-docstring
        permissions = (
            RepoPermission.view_repo,
            RepoPermission.import_course,
            RepoPermission.manage_taxonomy,
            RepoPermission.add_edit_metadata,
            RepoPermission.manage_repo_users,
        )


def get_preview_url(resource, org=None, course_number=None, run=None):
    """
    Create a preview URL. Accepts optional kwargs to prevent
    database lookups, especially for during search engine indexing.
    Args:
        resource (LearningResource): LearningResource
        org (unicode): resource.course.org
        run (unicode): resource.course.run
        course_number (unicode): resource.course.course_number
    Returns:
        url (unicode): Preview URL for LearningResource.
    """
    if org is None:
        org = resource.course.org
    if course_number is None:
        course_number = resource.course.course_number
    if run is None:
        run = resource.course.run
    key = "{org}/{course}/{run}".format(
        org=org,
        course=course_number,
        run=run,
    )

    url_name = resource.url_name
    if url_name is None:
        # The parent query can be expensive if done repeatedly
        # but this is hopefully a rare case.
        current = resource.parent
        while current is not None:
            url_name = current.url_name
            if url_name is not None:
                break
            current = current.parent

    if url_name is None:
        path = "courseware"
        preview_id = ""
    else:
        path = "jump_to_id"
        preview_id = "/{0}".format(url_name)

    url_format = '{base_url}courses/{key}/{path}{preview_id}'
    return url_format.format(
        base_url=LORE_PREVIEW_BASE_URL,
        path=urllib_parse.quote(path),
        key=urllib_parse.quote(key),
        preview_id=urllib_parse.quote(preview_id),
    )

ui/forms.py
"""
Forms for LORE.
"""

from __future__ import unicode_literals

import logging
import uuid

from django.conf import settings
from django.core.files.storage import default_storage
from django.forms import (
    Form, FileField, ValidationError, ModelForm,
)
from django.db import transaction

from importer.tasks import import_file
from learningresources.models import Repository
from rest.tasks import track_task, IMPORT_TASK_TYPE

log = logging.getLogger(__name__)


class UploadForm(Form):
    """
    Form for allowing a user to upload an OLX course archive
    """
    course_file = FileField()

    def __init__(self, *args, **kwargs):
        """
        Fill in choice fields.
        """
        super(UploadForm, self).__init__(*args, **kwargs)

    def clean_course_file(self):
        """Only certain extensions are allowed."""
        upload = self.cleaned_data["course_file"]
        log.debug("checking filename %s", upload.name)
        for ext in (".zip", ".tar.gz", ".tgz"):
            if upload.name.endswith(ext):
                log.debug("the filename is good")
                upload.ext = ext
                log.debug("setting upload.ext to %s", ext)
                return upload
        log.debug("got to end, so the file is bad")
        raise ValidationError("Unsupported file type.")

    def save(self, user_id, repo_id, session):
        """
        Receives the request.FILES from the view.

        Args:
            user_id (int): primary key of the user uploading the course.
            repo_id (int): primary key of repository we're uploading to.
            session (SessionStore): User's session to store task data.
        """
        # Assumes a single file, because we only accept
        # one at a time.
        uploaded_file = self.cleaned_data["course_file"]

        # Save the uploaded file into a temp file.
        path = default_storage.save(
            '{prefix}/{random}{ext}'.format(
                prefix=settings.IMPORT_PATH_PREFIX,
                random=str(uuid.uuid4()),
                ext=uploaded_file.ext
            ),
            uploaded_file
        )
        task = import_file.delay(path, repo_id, user_id)

        repo_slug = Repository.objects.get(id=repo_id).slug
        # Save task data in session so we can keep track of it.
        track_task(session, task, IMPORT_TASK_TYPE, {
            "repo_slug": repo_slug,
            "path": path
        })


class RepositoryForm(ModelForm):
    """
    Form for the Repository object.
    """
    class Meta:  # pylint: disable=missing-docstring
        model = Repository
        fields = ("name", "description")

    # pylint: disable=signature-differs
    # The ModelForm.save() accepts "commit" and this doesn't, because
    # we always set commit=False then add the user because created_by is
    # not part of the form, and shouldn't be.
    @transaction.atomic
    def save(self, user):
        """
        Save a newly-created form.
        """
        repo = super(RepositoryForm, self).save(commit=False)
        repo.created_by = user
        repo.save()
        return repo

ui/templates/base.html
{% load compress staticfiles bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MIT - LORE {% block title %}{% endblock %}</title>
    {% compress js %}
    {# Special include for modernizr to load early #}
    <script type="text/javascript"
      src="{% static "bower/modernizr/modernizr.js" %}"
    ></script>
    {% endcompress %}
    <link
       href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700|Droid+Serif"
       rel="stylesheet"
       type="text/css"
     >

    {% compress css %}
    {# Vendor CSS #}
    <link
       rel="stylesheet"
       href="{% static "bower/components-font-awesome/css/font-awesome.css" %}"
    >
    <link rel="stylesheet" href="{% static "bower/icheck/skins/square/blue.css" %}">
    <link
       rel="stylesheet"
       href="{% static "bower/bootstrap/dist/css/bootstrap.css" %}"
     >
    <link
      rel="stylesheet"
      href="{% static "bower/select2/dist/css/select2.css" %}"
    >
    <link
      rel="stylesheet"
      href="{% static "bower/select2-bootstrap-theme/dist/select2-bootstrap.css" %}"
    >
    {# Site css #}
    <link rel="stylesheet" href="{% static "ui/css/slide-drawer.css" %}">
    <link rel="stylesheet" href="{% static "ui/css/mit-lore.css" %}">
    {% endcompress %}
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block extrahead %}
    {% endblock %}


  </head>
  <body>
    {% bootstrap_messages %}
    <nav class="navbar navbar-lore">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url "welcome" %}"><img src="{% static "ui/images/logo-mit-lore.png" %}" alt="MIT LORE" /></a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            {% block nav %}{% endblock %}
          </ul>
          <ul class="nav navbar-nav navbar-right navbar-utility">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle nav-highlight" data-toggle="dropdown" role="button" aria-expanded="false">{{ request.user.username }}<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{% url "cas_logout" %}?next_page=/"><i class="fa fa-sign-out"></i> Logout</a></li>
                {% block actions %}{% endblock %}
                <!-- <li><a href="#">Action</a></li> -->
                <!-- <li><a href="#">Another action</a></li> -->
                <!-- <li><a href="#">Something else here</a></li> -->
                <!-- <li class="divider"></li> -->
                <!-- <li><a href="#">Separated link</a></li> -->
              </ul>
            </li>
            {% block extranavbarright %}{% endblock %}
          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container-fluid -->
    </nav>
    <div class="container">
    {% block content %}
    {% endblock %}
      <footer>
        <div class="container">
          © 2015, Massachusetts Institute of Technology | Contact us: mitx-support@mit.edu
        </div>
      </footer>
    </div>
    {% compress js %}
    <script type="text/javascript"
      src="{% static "bower/retina.js/dist/retina.js" %}">
    </script>
    <script type="text/javascript"
      src="{% static "bower/requirejs/require.js" %}">
    </script>
    <script type="text/javascript" src="{% static "ui/js/require_config.js" %}">
    </script>
    <script type="text/javascript">
      require.config({
        baseUrl: "{% static "bower"%}",
        shim: SHIMS,
        paths: REQUIRE_PATHS,
        waitSeconds: 200
      });
      require(["jquery", "bootstrap"]);
    </script>
    {% endcompress %}
    {% block postcontent %}
    {% endblock %}
    {% if settings.GOOGLE_ANALYTICS_ID %}
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new
      Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', '{{ settings.GOOGLE_ANALYTICS_ID }}', 'auto');
      ga('send', 'pageview');
    </script>
    {% endif %}
  </body>
</html>

ui/templates/create_repo.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% block title %}Create Repository{% endblock %}
{% block content %}
<h1>Create repository</h1>
<form method="post" action="{% url 'create_repo' %}">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
  <button type="submit" class="btn btn-primary">
    {% bootstrap_icon "star" %} Add Repo
  </button>
  {% endbuttons %}
</form>
{% endblock %}

ui/templates/data.html
{% extends "base.html" %}
{% load staticfiles compress %}
{% block title %}Listing{% endblock %}
{% block content %}

<style>
.container {
  width: 100%;
}
</style>
<div id="data">

</div>
{% include "includes/resource_panel.html" %}
<!-- Modal -->
<div class="modal fade" id="progress-modal" tabindex="-1" role="dialog" aria-labelledby="progressModal">
  <div class="modal-dialog" role="document">
  </div>
</div>
<div id="confirmation-container"></div>
{% endblock %}
{% block postcontent %}
{{ block.super }}
{% compress js %}
<script type="text/jsx"
        src="{% static "ui/js/learningresources/learning_resources.jsx" %}">
</script>
<script type="text/jsx"
        src="{% static "ui/js/learningresources/static_assets.jsx" %}">
</script>
<script type="text/jsx"
        src="{% static "ui/js/util/confirmation_dialog.jsx" %}">
</script>
<script type="text/jsx"
        src="{% static "ui/js/util/icheckbox.jsx" %}">
</script>
<script type="text/jsx"
        src="{% static "ui/js/util/infinite_list.jsx" %}">
</script>
<script type="text/jsx"
        src="{% static "ui/js/util/react_overlay_loader.jsx" %}">
</script>
<script type="text/jsx"
        src="{% static "ui/js/util/select2_component.jsx" %}">
</script>
<script type="text/jsx"
        src="{% static "ui/js/util/status_box.jsx" %}">
</script>
<script type="text/jsx"
        src="{% static "ui/js/util/utils.jsx" %}">
</script>
<script type="text/jsx"
        src="{% static "ui/js/listing/lore_data_table.jsx" %}">
</script>
{% endcompress %}
<script type="text/javascript">
require(["jquery", "utils", "lore_data_table"],
        function($, Utils, LoreDataTable) {
  var repoSlug = "{{ repo.slug|escapejs }}";

  $(function() {
    Utils.getCollection("/api/v1/repositories/" + repoSlug + "/search/?page_size=1000").then(function(results) {
      LoreDataTable.loader(repoSlug, results, $("#data")[0]);
    });
  });
});
</script>
{% compress css %}
    <link
       rel="stylesheet"
       href="{% static "lib/css/index.min.css" %}" />
{% endcompress %}
{% endblock %}

ui/templates/listing.html
{% extends "repo_base.html" %}
{% block title %}Listing{% endblock %}
{% block content %}
    <div id="header"></div>
    <div class="col-md-3">
    </div>
    <div class="col-md-9 col-results">
        <div class="row grid-row-top">
            <div class="col-md-5"></div>
            <div class="col-md-7 text-right"></div>
        </div>
        {% for resource in resources %}
            <div class="row">
                <div class="col-md-10">
                    <div class="tile">
                        <div class="tile-icon tile-color-1">
                            <img class="ic-custom" height="18" width="24"
                                 src="http://pureui.com/c/mit/lore/build001/assets/images/ic-book@2x.png">
                        </div>
                        <div class="tile-content">
                            <h2>
                                <a href="{% url 'export' resource.id %}">
                                    {% if resource.title %}
                                        {{ resource.title }}
                                    {% else %}
                                        no title
                                    {% endif %}
                                </a>
                            </h2>

                            <div class="tile-blurb"> Description .. should be editable by user
                            </div>
                            <div class="tile-meta">
                                <span class="meta-item">{{ resource.course.course_number }}</span>
                                <span class="meta-item">{{ resource.course.run }}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="lore-pagination">
                {% if resources.has_other_pages %}
                    {% if resources.has_previous %}
                        <a href="{% url 'listing' repo.slug %}?page={{ resources.previous_page_number }}"><i
                                class="fa fa-angle-left"></i></a>
                    {% endif %}

                    {% if resources.has_next %}
                        <a href="{% url 'listing' repo.slug %}?page={{ resources.next_page_number }}"><i
                                class="fa fa-angle-right"></i></a>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
    </div>

{% endblock %}

ui/templates/repo_base.html
{% extends "base.html" %}
{% block nav %}
  {{ nav.super }}
   	{% if 'import_course' in perms_on_cur_repo %}
 	  <li>
 	  	<a href="{% url 'upload' repo.slug %}"><i class="fa fa-arrow-circle-o-right"></i> Import Course</a>
 	  </li>
 	{% endif %}
  	{% if 'manage_taxonomy' in perms_on_cur_repo %}
      <li>
        <a href="#0" class="btn-taxonomies"><i class="fa fa-cogs"></i> Manage Taxonomy</a>
      </li>
    {% endif %}
      <input type="hidden" id="repo_slug" value="{{ repo.slug }}" />
    {% if 'manage_repo_users' in perms_on_cur_repo %}
      <li>
        <a href="#repo-members" class="btn-members"><i class="fa fa-users"></i> Manage Members</a>
      </li>
    {% endif %}
  {% endblock %}

  {% block extranavbarright %}
  <span class="text-repo-name">Repository: <a href="{% url 'repositories' repo.slug %}">{{ repo.name }}</a></span>
  {% endblock %}

ui/templates/upload.html
{% extends "repo_base.html" %}
{% load bootstrap3 %}
{% block title %}Upload Course{% endblock %}
{% block nav %}
{% endblock %}
{% block content %}

<h1>Upload content in OLX format</h1>
<form method="post" action="{% url 'upload' repo.slug %}" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-primary">
        {% bootstrap_icon "star" %} Upload Course
    </button>
</form>

{% endblock %}

ui/templates/vocabulary.html
{% extends "base.html" %}
{% block content %}
    {% if vocabulary_id %}
        <form action="{% url 'edit_vocabulary' repo_slug=repo_slug vocab_slug=vocab_slug %}" method="post">
    {% else %}
        <form action="{% url 'create_vocabulary' repo_slug=repo_slug %}" method="post">
    {% endif %}
        {%  csrf_token %}
        <table>
        {{ form }}
        </table>
        <input type="submit" value="Submit" />
    </form>
{% endblock %}

ui/templates/welcome.html
{% extends "base.html" %}
{% block content %}
    <div class="section-header">
        <div class="row">
            <div class="col-md-2 col-md-offset-5">{% if perms.learningresources.add_repository %}<a href="{% url 'create_repo' %}" role="button"
                                                     class="btn btn-primary btn-large">Create repository</a>
                {% else %}
                    <a href="mailto:{{ support_email }}?subject=[LORE-app]Request%20permission%20to%20create%20repositories" role="button"
                       class="btn btn-primary btn-large">Request permission to create repositories</a>
                {% endif %}
            </div>
        </div>
    </div>

    {% if repos %}
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <h2>Your repositories</h2>
                <ul class="repos">
                    {% for repo in repos %}
                        <li>
                            <a href="{% url 'repositories' repo.slug %}">{{ repo.name }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-md-4"></div>
        </div>
    {% endif %}
{% endblock %}